spring:
  main:
    banner-mode: "off"
    # We do not need Tomcat running (this application runs from console)
    web-environment: false

kafka:
  broker: localhost:29092
  topic: avro.topic.example
schema:
  registry:
    url: http://localhost:8081
    connection-timeout: 10000
    read-timeout: 10000