# Spring Boot configuration properties
spring:
  application:
    name: web-services-spring-webreactive-client
  main:
    banner-mode: "LOG"

# By default Spring Boot uses logback.
# logging:
#   level:
#     org:
#       springframework: info
#     ROOT: info
   
# Using log4j2 (just for fun) It requires exclusions in spring-boot-starter because by default
# Spring Boot will pick up the logback dependency :/
logging:
  config: classpath:log4j2.xml


# Application properties
app:
  uri:
    host:
      url: http://localhost:8080/spring-webreactive-resources-1.0-SNAPSHOT
      read-timeout: 10000
      write-timeout: 10000
      connection-timeout: 10000
