# Spring Boot configuration properties
spring:
  application:
    name: web-services-spring-rest-client
  main:
    banner-mode: "LOG"
    # We do not need Tomcat running (this application runs from console)
    web-environment: false
  
# By default Spring Boot uses logback.
# logging:
#   level:
#     org:
#       springframework: info
#     ROOT: info
   
# Using log4j2 (just for fun) It requires exclusions in spring-boot-starter because by default
# Spring Boot will pick up the logback dependency :/
logging:
  config: classpath:log4j2.xml
  

# Application properties
app:
  url:
    base: http://localhost:8080