# Spring Boot configuration properties
spring:
  application:
    name: web-services-spring-pact-client
  main:
    banner-mode: "LOG"
    # We do not need Tomcat running (this application runs from console)
    web-environment: false
  
# By default Spring Boot uses logback.
# logging:
#   level:
#     org:
#       springframework: info
#     ROOT: info
   
# Using log4j2 (just for fun) It requires exclusions in spring-boot-starter because by default
# Spring Boot will pick up the logback dependency :/
logging:
  config: classpath:log4j2.xml
    
feign:
  client:
    config:
      web-services-spring-pact-server:
        url: localhost:8000
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        
web-services-spring-pact-server:
  ribbon:
    listOfServers: localhost:8000
    ConnectTimeout: 10000
    ReadTimeout: 10000
    MaxTotalHttpConnections: 50
    MaxConnectionsPerHost: 10